/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c4c6d2",
        "secondary-fixed": "#d7e2ff",
        "tertiary-fixed-dim": "#c0c7cf",
        "on-surface": "#1a1c1e",
        "on-secondary-fixed-variant": "#004491",
        "primary-fixed-dim": "#aec6ff",
        "inverse-on-surface": "#f0f0f3",
        "surface-container": "#eeeef0",
        "on-primary-fixed-variant": "#224583",
        "on-tertiary-container": "#939aa1",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "tertiary": "#161d23",
        "primary-container": "#002f6c",
        "surface": "#f9f9fc",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3f6",
        "primary-fixed": "#d8e2ff",
        "on-background": "#1a1c1e",
        "inverse-primary": "#aec6ff",
        "error": "#ba1a1a",
        "secondary-container": "#659dfe",
        "on-secondary-fixed": "#001a40",
        "inverse-surface": "#2f3133",
        "secondary-fixed-dim": "#acc7ff",
        "secondary": "#115cb9",
        "on-secondary-container": "#003370",
        "tertiary-fixed": "#dce3eb",
        "surface-container-high": "#e8e8ea",
        "on-tertiary-fixed-variant": "#40484e",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-tint": "#3c5d9c",
        "surface-variant": "#e2e2e5",
        "surface-bright": "#f9f9fc",
        "outline": "#747781",
        "on-tertiary-fixed": "#151c22",
        "background": "#f9f9fc",
        "on-surface-variant": "#434750",
        "primary": "#001b44",
        "surface-dim": "#dadadc",
        "on-primary-fixed": "#001a42",
        "surface-container-highest": "#e2e2e5",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2b3238",
        "on-primary-container": "#7999dc",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "unit": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "gutter": "24px",
        "container-max": "800px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-md": ["Public Sans", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
