[build]
  base = "frontend"
  command = "rm -rf ../package-lock.json package-lock.json ../node_modules node_modules && npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
